---
- name: Install WinSwitch
  block:
    - name: Add WinSwitch apt key
      apt_key:
        url: https://winswitch.org/gpg.asc
        state: present

    - name: Add Winswitch Repository
      apt_repository:
        repo: deb http://winswitch.org/ {{ ansible_distribution_release }} main
        state: present
        update_cache: True

    - name: Install Winswitch
      apt:
        name: winswitch
        state: present
  become: True
